In [1]:
import warnings
warnings.filterwarnings('ignore') 
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("recom.csv")

In [3]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp
0  12.801685  0.012360                57         62        71        52
1  12.851654  0.004172                57         58        73        43
2  12.776774  0.000000                56         58        69        46
3  12.942001  0.031747                62         56        70        43
4  12.984652  0.000000                65         56        70        42

In [4]:
clay1=np.repeat('clay',1200)

In [5]:
clay1=clay1.reshape(1200,1)
clay1

array([['clay'],
       ['clay'],
       ['clay'],
       ...,
       ['clay'],
       ['clay'],
       ['clay']], dtype='<U4')

In [6]:
sandy1=np.repeat('sandy',1300)
sandy1=sandy1.reshape(1300,1)
good1=np.repeat('good_bio_cond',1300)
good1=good1.reshape(1300,1)

In [7]:
al1=np.repeat('alkaline',1300)
al1=al1.reshape(1300,1)
excellent=np.repeat('excellent_bio_cond',1100)
excellent=excellent.reshape(1100,1)

In [8]:
chalky1=np.repeat('chalky ',177)
chalky1=chalky1.reshape(177,1)
poor=np.repeat('poor_bio_cond',1577)
poor=poor.reshape(1577,1)

In [9]:
soil1=np.concatenate((clay1,sandy1, al1, chalky1),axis=0)
bio_cond = np.concatenate((good1,excellent, poor),axis=0)

In [10]:
soil1

array([['clay'],
       ['clay'],
       ['clay'],
       ...,
       ['chalky '],
       ['chalky '],
       ['chalky ']], dtype='<U8')

In [11]:
from random import shuffle

In [12]:
print (soil1)

[['clay']
 ['clay']
 ['clay']
 ...
 ['chalky ']
 ['chalky ']
 ['chalky ']]


In [13]:
np.random.shuffle(soil1)
np.random.shuffle(bio_cond)

In [14]:
soil1

array([['sandy'],
       ['sandy'],
       ['alkaline'],
       ...,
       ['sandy'],
       ['clay'],
       ['sandy']], dtype='<U8')

In [15]:
data['soil']=soil1

In [16]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  
0     sandy  
1     sandy  
2  alkaline  
3  alkaline  
4      clay

In [17]:
df = pd.DataFrame(data)

In [18]:
one = pd.get_dummies(df['soil'])

In [19]:
one['alkaline']
df['alkaline']=one['alkaline']
df['sandy']=one['sandy']
df['chalky'] = one['chalky ']
df['clay']=one['clay']

In [20]:
df.drop(['soil'],axis=1)

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0     12.801685  0.012360                57         62        71        52   
1     12.851654  0.004172                57         58        73        43   
2     12.776774  0.000000                56         58        69        46   
3     12.942001  0.031747                62         56        70        43   
4     12.984652  0.000000                65         56        70        42   
...         ...       ...               ...        ...       ...       ...   
3972  12.959730  0.000000                30         72        85        58   
3973  12.985416  0.000000                30         70        87        52   
3974  12.947405  0.000300                33         70        86        53   
3975  12.771689  0.000000                35         69        85        53   
3976  12.845779  0.010131                36         70        86        53   

      alkaline  sandy  chalky  clay  
0            0      1       0     0  
1            0      1       0     0  
2            1      0       0     0  
3            1      0       0     0  
4            0      0       0     1  
...        ...    ...     ...   ...  
3972         0      0       0     1  
3973         0      0       0     1  
3974         0      1       0     0  
3975         0      0       0     1  
3976         0      1       0     0  

[3977 rows x 10 columns]

In [21]:
data['bio']=bio_cond

In [22]:
df = pd.DataFrame(data)

In [23]:
one = pd.get_dummies(df['bio'])

In [24]:
df.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  
0     sandy         0      1       0     0  excellent_bio_cond  
1     sandy         0      1       0     0       poor_bio_cond  
2  alkaline         1      0       0     0       poor_bio_cond  
3  alkaline         1      0       0     0       good_bio_cond  
4      clay         0      0       0     1       poor_bio_cond

In [25]:
one.head()

excellent_bio_cond  good_bio_cond  poor_bio_cond
0                   1              0              0
1                   0              0              1
2                   0              0              1
3                   0              1              0
4                   0              0              1

In [26]:
df['excellent_bio_cond']=one['excellent_bio_cond']
df['poor_bio_cond']=one['poor_bio_cond']
df['good_bio_cond'] = one['good_bio_cond']

In [27]:
data['excellent']=df['excellent_bio_cond']
data['poor']=df['poor_bio_cond']
data['good']=df['good_bio_cond']

In [28]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0  excellent_bio_cond   
1     sandy         0      1       0     0       poor_bio_cond   
2  alkaline         1      0       0     0       poor_bio_cond   
3  alkaline         1      0       0     0       good_bio_cond   
4      clay         0      0       0     1       poor_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  
0                   1              0              0          1     0     0  
1                   0              1              0          0     1     0  
2                   0              1              0          0     1     0  
3                   0              0              1          0     0     1  
4                   0              1              0          0     1     0

In [29]:
data.drop(['bio','soil'],axis=1)
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0  excellent_bio_cond   
1     sandy         0      1       0     0       poor_bio_cond   
2  alkaline         1      0       0     0       poor_bio_cond   
3  alkaline         1      0       0     0       good_bio_cond   
4      clay         0      0       0     1       poor_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  
0                   1              0              0          1     0     0  
1                   0              1              0          0     1     0  
2                   0              1              0          0     1     0  
3                   0              0              1          0     0     1  
4                   0              1              0          0     1     0

In [30]:
df2 = data.values

In [31]:
df2.shape

(3977, 18)

In [32]:
data['yield'] = 0

In [33]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0  excellent_bio_cond   
1     sandy         0      1       0     0       poor_bio_cond   
2  alkaline         1      0       0     0       poor_bio_cond   
3  alkaline         1      0       0     0       good_bio_cond   
4      clay         0      0       0     1       poor_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  \
0                   1              0              0          1     0     0   
1                   0              1              0          0     1     0   
2                   0              1              0          0     1     0   
3                   0              0              1          0     0     1   
4                   0              1              0          0     1     0   

   yield  
0      0  
1      0  
2      0  
3      0  
4      0

In [34]:
a= 0
b = 0
c= 0
d = 0
arr = np.zeros((3977,1))


for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.005)) and (df2[i, 2] <60) and (df2[i, 3] > 55) and ((df2[i, 10] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        b = b + 1
        arr[i,0] = 2
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] > 0.5)) and (df2[i, 2] <50) and (df2[i, 3] > 45) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        c= c + 1
        arr[i,0] = 3
        
for i in range(3977):
    if(((df2[i, 0] < 12.8)  or (df2[i, 1] == 0.0)) and (df2[i, 2] <90) and (df2[i, 3] < 90) and ((df2[i, 10] == 1.0) or (df2[i, 9] == 1.0) or (df2[i, 7] == 1.0) or (df2[i, 8] == 1.0))):
        #print i
        d= d + 1
        arr[i,0] = 4
        
for i in range(3977):
    if(((df2[i, 0] > 12.6 and df2[i, 0] < 13.5)  or (df2[i, 1] > 0.000001)) and (df2[i, 2] > 40 and df2[i, 2] < 100) and (df2[i, 3] > 52 and df2[i, 3] < 100) and (df2[i, 10] == 1.0)  ):
        #print i
        a = a + 1
        arr[i,0] = 1
        


In [35]:
print (arr)
arr.reshape(3977,1)

[[2.]
 [0.]
 [4.]
 ...
 [0.]
 [4.]
 [2.]]


array([[2.],
       [0.],
       [4.],
       ...,
       [0.],
       [4.],
       [2.]])

In [36]:
data['millet yield']=arr

In [37]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  \
0     sandy         0      1       0     0  excellent_bio_cond   
1     sandy         0      1       0     0       poor_bio_cond   
2  alkaline         1      0       0     0       poor_bio_cond   
3  alkaline         1      0       0     0       good_bio_cond   
4      clay         0      0       0     1       poor_bio_cond   

   excellent_bio_cond  poor_bio_cond  good_bio_cond  excellent  poor  good  \
0                   1              0              0          1     0     0   
1                   0              1              0          0     1     0   
2                   0              1              0          0     1     0   
3                   0              0              1          0     0     1   
4                   0              1              0          0     1     0   

   yield  millet yield  
0      0           2.0  
1      0           0.0  
2      0           4.0  
3      0           0.0  
4      0           1.0

In [38]:
data = data.drop(['excellent_bio_cond','poor_bio_cond','good_bio_cond'],axis=1)

In [39]:
data.head()

Moisture  rainfall  Average Humidity  Mean Temp  max Temp  Min temp  \
0  12.801685  0.012360                57         62        71        52   
1  12.851654  0.004172                57         58        73        43   
2  12.776774  0.000000                56         58        69        46   
3  12.942001  0.031747                62         56        70        43   
4  12.984652  0.000000                65         56        70        42   

       soil  alkaline  sandy  chalky  clay                 bio  excellent  \
0     sandy         0      1       0     0  excellent_bio_cond          1   
1     sandy         0      1       0     0       poor_bio_cond          0   
2  alkaline         1      0       0     0       poor_bio_cond          0   
3  alkaline         1      0       0     0       good_bio_cond          0   
4      clay         0      0       0     1       poor_bio_cond          0   

   poor  good  yield  millet yield  
0     0     0      0           2.0  
1     1     0      0           0.0  
2     1     0      0           4.0  
3     0     1      0           0.0  
4     1     0      0           1.0

In [40]:
data = data.drop(['soil','bio','excellent','poor','good','yield'],axis = 1)

In [41]:
a = np.unique(data['millet yield'])
a

array([0., 1., 2., 3., 4.])

In [42]:
data.to_csv('finalyield.csv')

In [43]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
dt = pd.read_csv('finalyield.csv')

In [45]:
X = dt.drop(['millet yield'],axis=1)
Y = dt['millet yield']
Y= Y.to_frame()
Y.head()

millet yield
0           2.0
1           0.0
2           4.0
3           0.0
4           1.0

In [46]:
Y = Y.values

In [47]:
onehot_encoder = OneHotEncoder(sparse=False)
Y = Y.reshape(len(Y), 1)
onehot_encoded = onehot_encoder.fit_transform(Y)
print (onehot_encoded)

[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 ...
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]


In [48]:
import matplotlib.pyplot as plt
# Plot histogram grid
data.hist(figsize=(15,15), xrot=-45, bins=10) ## Display the labels rotated by 45 degress
plt.show()

<Figure size 1500x1500 with 12 Axes>

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.2,random_state=0)

In [51]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
rf = RandomForestClassifier(n_estimators=140)
rf.fit(X_train,y_train)
print (rf.score(X_test,y_test))

0.9962311557788944


In [53]:
from matplotlib import pyplot as plt

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
clf = LogisticRegression()

In [56]:
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [57]:
y_pred=clf.predict(X_test)

In [58]:
print (clf.score(X_test,y_test))

0.6758793969849246


In [59]:
from sklearn import svm

In [60]:
clfs = svm.SVC()

In [61]:
clfs.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [62]:
y_pred = clfs.predict(X_test)

In [63]:
print (clfs.score(X_test,y_test))

0.40954773869346733


In [64]:
test_vector = np.reshape(np.asarray([12.737998,0.026821,61,56,70,42,1.0,0.0,0.0,0.0,0.0]),(1,11))
p = int(rf.predict(test_vector)[0])
yield_list = ['Poor Yield','Below Average','Average','Good Yield','Excellent Yield']
print (yield_list[p])

Excellent Yield
